"""
Pydantic Schemas Package
"""

from app.schemas.analytics import (
    AnalyticsPeriodParams,
    BenchmarkItem,
    BenchmarkResponse,
    CategoryBreakdownItem,
    CategoryBreakdownResponse,
    InsightItem,
    InsightsResponse,
    MerchantAnalysisItem,
    MerchantAnalysisResponse,
    PredictionDataPoint,
    RecurringTransactionItem,
    RecurringTransactionsResponse,
    SpendingPredictionsResponse,
    SpendingSummaryResponse,
    SpendingTrendsResponse,
    TrendDataPoint,
    TrendParams,
)
from app.schemas.budget import (
    BudgetCreateRequest,
    BudgetResponse,
    BudgetSummaryResponse,
    BudgetUpdateRequest,
    BudgetWithProgressResponse,
)
from app.schemas.category import (
    CategoryCreateRequest,
    CategoryResponse,
    CategoryTreeResponse,
    CategoryUpdateRequest,
    CategoryWithChildrenResponse,
    CategoryWithStatsResponse,
)
from app.schemas.common import (
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    MessageResponse,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.transaction import (
    TransactionBulkCreateRequest,
    TransactionBulkCreateResponse,
    TransactionCreateRequest,
    TransactionDetailResponse,
    TransactionFilterParams,
    TransactionResponse,
    TransactionSearchRequest,
    TransactionSummary,
    TransactionUpdateRequest,
)
from app.schemas.upload import (
    ConfirmUploadRequest,
    FileType,
    ParsedTransaction,
    ParsePreviewResponse,
    UploadHistoryItem,
    UploadHistoryResponse,
    UploadInitResponse,
    UploadStatus,
    UploadStatusResponse,
)
from app.schemas.user import (
    AuthResponse,
    ChangePasswordRequest,
    LoginResponse,
    RefreshTokenRequest,
    TokenResponse,
    UserLoginRequest,
    UserProfileResponse,
    UserRegisterRequest,
    UserResponse,
    UserUpdateRequest,
)

__all__ = [
    # Common
    "ErrorDetail",
    "ErrorResponse",
    "HealthResponse",
    "MessageResponse",
    "PaginatedResponse",
    "PaginationParams",
    # User
    "UserRegisterRequest",
    "UserLoginRequest",
    "ChangePasswordRequest",
    "UserUpdateRequest",
    "RefreshTokenRequest",
    "UserResponse",
    "UserProfileResponse",
    "TokenResponse",
    "LoginResponse",
    "AuthResponse",
    # Transaction
    "TransactionCreateRequest",
    "TransactionUpdateRequest",
    "TransactionBulkCreateRequest",
    "TransactionFilterParams",
    "TransactionSearchRequest",
    "TransactionResponse",
    "TransactionDetailResponse",
    "TransactionBulkCreateResponse",
    "TransactionSummary",
    # Category
    "CategoryCreateRequest",
    "CategoryUpdateRequest",
    "CategoryResponse",
    "CategoryWithChildrenResponse",
    "CategoryWithStatsResponse",
    "CategoryTreeResponse",
    # Budget
    "BudgetCreateRequest",
    "BudgetUpdateRequest",
    "BudgetResponse",
    "BudgetWithProgressResponse",
    "BudgetSummaryResponse",
    # Analytics
    "AnalyticsPeriodParams",
    "TrendParams",
    "SpendingSummaryResponse",
    "CategoryBreakdownItem",
    "CategoryBreakdownResponse",
    "TrendDataPoint",
    "SpendingTrendsResponse",
    "InsightItem",
    "InsightsResponse",
    "PredictionDataPoint",
    "SpendingPredictionsResponse",
    "BenchmarkItem",
    "BenchmarkResponse",
    "MerchantAnalysisItem",
    "MerchantAnalysisResponse",
    "RecurringTransactionItem",
    "RecurringTransactionsResponse",
    # Upload
    "UploadStatus",
    "FileType",
    "UploadInitResponse",
    "UploadStatusResponse",
    "UploadHistoryItem",
    "UploadHistoryResponse",
    "ParsedTransaction",
    "ParsePreviewResponse",
    "ConfirmUploadRequest",
]
